const dataThing = [
  {
    answer: "Anomalia",
    tips: [
      "Pode ser encontrada em várias áreas da ciência.",
      "É uma diferença ou desvio do que é normal.",
      "Às vezes, é notada em estudos estatísticos.",
      "Pode ser genética ou ambiental.",
      "Pode estar relacionada a estruturas físicas ou funções biológicas.",
      "Em astronomia, pode indicar um comportamento inesperado.",
      "Pode ser detectada através de exames médicos.",
      "Muitas vezes, requer investigação adicional.",
      "Na informática, pode ser um bug ou glitch.",
      "Pode ser um sinal de algo maior ou mais complexo.",
      "Pode ser vista em fenômenos naturais.",
      "Pode indicar uma mutação genética.",
      "Em estatística, pode ser um outlier.",
      "Pode ocorrer em organismos vivos e sistemas mecânicos.",
      "Pode levar a novas descobertas científicas.",
    ],
  },
  {
    answer: "Malária",
    tips: [
      "É transmitida por um vetor.",
      "Afeta milhões de pessoas ao redor do mundo.",
      "Foi descoberta no século XIX.",
      "Tem sintomas que incluem febre e calafrios.",
      "Pode ser fatal se não tratada.",
      "É mais comum em regiões tropicais e subtropicais.",
      "O vetor mais conhecido é um tipo de inseto.",
      "Pode causar anemia.",
      "É causada por um parasita.",
      "Tem um ciclo de vida complexo envolvendo dois hospedeiros.",
      "Pode ser prevenida com medicação e medidas de proteção.",
      "A prevenção inclui o uso de mosquiteiros.",
      "É uma das doenças mais antigas conhecidas pela humanidade.",
      "Existem vacinas em desenvolvimento para combatê-la.",
      "O inseto vetor é o mosquito Anopheles.",
    ],
  },
  {
    answer: "Apneia do Sono",
    tips: [
      "É um distúrbio relacionado ao sono.",
      "Pode afetar a qualidade de vida.",
      "É mais comum em pessoas acima do peso.",
      "Pode causar fadiga diurna.",
      "Muitas vezes, não é percebida pela própria pessoa.",
      "Pode ser detectada por um parceiro de cama.",
      "Está relacionada à respiração interrompida durante o sono.",
      "Pode aumentar o risco de doenças cardiovasculares.",
      "É tratável com mudanças de estilo de vida e aparelhos médicos.",
      "Pode ser diagnosticada através de um estudo do sono.",
      "Existem diferentes tipos desse distúrbio.",
      "Pode causar ronco alto.",
      "Alguns casos requerem o uso de um CPAP.",
      "Pode levar a episódios frequentes de asfixia durante a noite.",
      "É uma condição onde a respiração para e recomeça repetidamente durante o sono.",
    ],
  },
  {
    answer: "Depressão",
    tips: [
      "É um transtorno mental.",
      "Pode afetar qualquer pessoa, independentemente da idade.",
      "Os sintomas incluem tristeza persistente.",
      "Pode interferir nas atividades diárias.",
      "Afeta o humor e a percepção de si mesmo.",
      "Muitas vezes, não tem uma causa única.",
      "Pode ser desencadeada por eventos estressantes.",
      "Pode ser tratada com terapia e medicação.",
      "É uma das principais causas de incapacidade global.",
      "Pode causar perda de interesse em atividades anteriormente prazerosas.",
      "Pode estar acompanhada de alterações no apetite e no sono.",
      "Afeta milhões de pessoas em todo o mundo.",
      "Pode levar a pensamentos suicidas.",
      "O tratamento pode incluir antidepressivos.",
      "É uma condição caracterizada por sentimentos de desesperança e perda de interesse em atividades diárias.",
    ],
  },
  {
    answer: "Pneumonia",
    tips: [
      "Afeta principalmente o sistema respiratório.",
      "É uma infecção que pode ser bacteriana, viral ou fúngica.",
      "Pode causar febre alta e calafrios.",
      "Frequentemente, é acompanhada por tosse com catarro.",
      "Pode ocorrer após um resfriado ou gripe.",
      "É mais perigosa para crianças pequenas e idosos.",
      "Pode ser diagnosticada através de exames de imagem, como radiografias.",
      "Os sintomas podem incluir dor no peito ao respirar.",
      "Pode levar a falta de ar e dificuldade para respirar.",
      "Em casos graves, pode requerer hospitalização.",
      "É tratável com antibióticos se for bacteriana.",
      "A vacinação pode ajudar a preveni-la.",
      "Pode causar confusão mental em idosos.",
      "A recuperação completa pode levar várias semanas.",
      "É uma inflamação dos pulmões.",
    ],
  },
  {
    answer: "Esclerose Múltipla",
    tips: [
      "É uma doença autoimune.",
      "Afeta o sistema nervoso central.",
      "Pode causar fraqueza muscular e fadiga.",
      "É mais comum em mulheres.",
      "Os sintomas podem ser variados e imprevisíveis.",
      "Pode afetar a visão, causando visão dupla ou perda de visão.",
      "A causa exata é desconhecida.",
      "É caracterizada pela degradação da mielina.",
      "Pode causar problemas de coordenação e equilíbrio.",
      "Os surtos podem ser seguidos de períodos de remissão.",
      "A progressão pode ser lenta ou rápida.",
      "Os tratamentos podem incluir medicamentos imunomoduladores.",
      "O diagnóstico é feito através de exames de ressonância magnética.",
      "A fisioterapia pode ajudar a manejar os sintomas.",
      "É uma doença crônica que afeta o cérebro e a medula espinhal.",
    ],
  },
  {
    answer: "Câncer",
    tips: [
      "É uma doença caracterizada pelo crescimento celular descontrolado.",
      "Pode afetar qualquer parte do corpo.",
      "Existem muitos tipos diferentes.",
      "Pode ser causada por fatores genéticos e ambientais.",
      "Fumar é um dos principais fatores de risco.",
      "A detecção precoce pode melhorar significativamente o prognóstico.",
      "Pode se espalhar para outras partes do corpo através da metástase.",
      "O tratamento pode incluir cirurgia, quimioterapia e radioterapia.",
      "A pesquisa está continuamente buscando novas formas de tratamento.",
      "Alguns tipos podem ser prevenidos com vacinas.",
      "Pode causar perda de peso inexplicável.",
      "A dor pode ser um sintoma comum em estágios avançados.",
      "O rastreamento regular pode ajudar na detecção precoce.",
      "Pode afetar pessoas de todas as idades.",
      "É uma doença onde células anormais crescem de forma incontrolável.",
    ],
  },
  {
    answer: "Meningite",
    tips: [
      "É uma inflamação das membranas que envolvem o cérebro e a medula espinhal.",
      "Pode ser causada por bactérias, vírus ou fungos.",
      "Os sintomas iniciais podem ser semelhantes aos de uma gripe.",
      "Pode causar dor de cabeça intensa e rigidez no pescoço.",
      "Pode ser acompanhada por febre alta e sensibilidade à luz.",
      "A detecção precoce é crucial para o tratamento eficaz.",
      "Pode causar confusão ou alterações de consciência.",
      "É mais comum em crianças pequenas e adolescentes.",
      "O tratamento varia dependendo da causa subjacente.",
      "A vacinação pode prevenir alguns tipos.",
      "Pode resultar em complicações graves se não tratada prontamente.",
      "A punção lombar é um procedimento diagnóstico comum.",
      "Pode levar à perda auditiva ou problemas neurológicos.",
      "Em casos graves, pode ser fatal.",
      "É uma infecção das membranas protetoras do cérebro e da medula espinhal.",
    ],
  },
  {
    answer: "Autenticidade",
    tips: [
      "É um conceito muitas vezes associado à sinceridade e verdade.",
      "É importante em várias áreas da vida, incluindo relações pessoais e profissionais.",
      "Está relacionada à coerência entre ações e valores pessoais.",
      "Pode ser difícil de alcançar em um mundo cheio de pressões sociais.",
      "Pessoas que a possuem são frequentemente vistas como confiáveis.",
      "É frequentemente discutida em contextos filosóficos e psicológicos.",
      "Pode ser percebida através da comunicação aberta e honesta.",
      "É um atributo valorizado em líderes e figuras públicas.",
      "Não significa perfeição, mas sim consistência e honestidade.",
      "Está ligada ao conceito de auto aceitação.",
      "Pode ser cultivada através de introspecção e autoconhecimento.",
      "É frequentemente associada à originalidade.",
      "As pessoas a buscam como uma forma de viver uma vida mais plena.",
      "Pode ser um diferencial em um mundo de falsidades e aparências.",
      "É a qualidade de ser verdadeiro consigo mesmo e com os outros.",
    ],
  },
  {
    answer: "Nostalgia",
    tips: [
      "É uma emoção complexa.",
      "Geralmente envolve uma saudade do passado.",
      "Pode ser desencadeada por cheiros, sons ou lugares.",
      "Muitas vezes, é associada a memórias felizes.",
      "Pode envolver um desejo de voltar a um tempo ou lugar específico.",
      "Foi originalmente considerada uma condição médica.",
      "Pode ser tanto positiva quanto negativa.",
      "Pode proporcionar conforto em tempos de estresse.",
      "É frequentemente explorada na música e na literatura.",
      "Pode ser sentida por pessoas de todas as idades.",
      "Frequentemente envolve lembranças da infância.",
      "Pode causar uma sensação de perda ou tristeza.",
      "É um tema comum em filmes e séries de TV.",
      "Pode fortalecer os laços sociais e a identidade pessoal.",
      "É um sentimento de saudade de tempos passados.",
    ],
  },
  {
    answer: "Altruísmo",
    tips: [
      "É uma qualidade moral e ética.",
      "Envolve ações realizadas em benefício de outros.",
      "É frequentemente associado ao sacrifício pessoal.",
      "Pode ser observado em várias espécies animais.",
      "É uma característica valorizada em muitas culturas.",
      "Está relacionado à empatia e compaixão.",
      "Pode ser incentivado por valores religiosos ou filosóficos.",
      "É o oposto do egoísmo.",
      "Suas ações podem não trazer benefícios imediatos para o praticante.",
      "É estudado em psicologia e sociologia.",
      "Pode ser motivado por um desejo genuíno de ajudar.",
      "Algumas teorias evolutivas explicam como ele pode ter surgido.",
      "Pode envolver doação de tempo, recursos ou até mesmo sangue.",
      "Muitas organizações de caridade são baseadas nesse princípio.",
      "É a prática de preocupação com o bem-estar dos outros.",
    ],
  },
  {
    answer: "Clarividência",
    tips: [
      "É um fenômeno paranormal.",
      "Envolve a percepção além dos sentidos normais.",
      "Pode ser relacionada a visões do passado, presente ou futuro.",
      "Muitas vezes, é associada a médiuns e psíquicos.",
      "A palavra vem do francês e significa 'visão clara'.",
      "É um tema comum em histórias de mistério e ficção científica.",
      "Pode ocorrer espontaneamente ou ser desenvolvida.",
      "Algumas culturas a consideram um dom espiritual.",
      "É frequentemente debatida em círculos científicos.",
      "Pode ser usada em leituras de tarot ou outras práticas divinatórias.",
      "Às vezes, é considerada uma forma de intuição aguçada.",
      "Pode ser vista como uma habilidade ou talento especial.",
      "Muitos relatos envolvem sonhos premonitórios.",
      "Pode ser investigada através de estudos de parapsicologia.",
      "É a capacidade de obter informações além dos meios normais de percepção.",
    ],
  },
  {
    answer: "Melancolia",
    tips: [
      "É uma emoção profunda e complexa.",
      "Pode ser sentida sem um motivo aparente.",
      "Está frequentemente associada à tristeza e reflexão.",
      "Pode ser uma resposta a experiências de perda ou desilusão.",
      "É um tema recorrente na literatura e arte.",
      "Pode envolver uma sensação de vazio ou falta.",
      "Foi considerada uma das quatro 'humores' na medicina antiga.",
      "Às vezes, é vista como um estado criativo.",
      "Pode ser desencadeada por música ou ambientes específicos.",
      "Pode durar desde alguns momentos até longos períodos.",
      "Não é necessariamente considerada uma condição clínica.",
      "Pode levar à introspecção profunda.",
      "É frequentemente retratada em pinturas de épocas passadas.",
      "Pode ser uma fonte de inspiração artística.",
      "É um estado de tristeza pensativa e contemplativa.",
    ],
  },
  {
    answer: "Alienação",
    tips: [
      "É um conceito frequentemente discutido em sociologia e filosofia.",
      "Pode ser um sentimento de desconexão ou estranhamento.",
      "Pode ocorrer em contextos de trabalho, sociedade ou pessoal.",
      "É um tema central nas obras de Karl Marx.",
      "Pode ser causada por estruturas sociais opressivas.",
      "Muitas vezes, está associada à perda de sentido ou propósito.",
      "Pode ocorrer quando as pessoas se sentem isoladas de suas comunidades.",
      "É frequentemente explorada na literatura e no cinema.",
      "Pode ser uma consequência da industrialização e modernização.",
      "Tem uma relação com a falta de controle sobre a própria vida.",
      "Pode levar a sentimentos de impotência ou desesperança.",
      "Pode ser exacerbada por condições econômicas e políticas.",
      "Às vezes, é abordada em contextos de saúde mental.",
      "Pode afetar tanto indivíduos quanto grupos.",
      "É um estado de distanciamento ou separação de algo ou alguém.",
    ],
  },
  {
    answer: "Alfajor",
    tips: [
      "É um doce tradicional em vários países da América Latina.",
      "Geralmente é feito com duas camadas de massa.",
      "O recheio pode variar, mas doce de leite é muito comum.",
      "Muitas vezes, é coberto com chocolate ou açúcar em pó.",
      "Tem origem espanhola, mas foi adaptado em diversos países.",
      "Pode incluir ingredientes como coco ou nozes.",
      "Na Argentina, é muito popular e há diversas variações regionais.",
      "Pode ser encontrado em versões caseiras e industriais.",
      "É um presente comum durante festividades e comemorações.",
      "O nome pode derivar de uma palavra árabe.",
      "Pode ser feito com farinha de trigo ou amido de milho.",
      "Tem uma textura macia e um sabor doce e rico.",
      "É vendido em muitos cafés e padarias na América Latina.",
      "A versão uruguaia é conhecida por seu sabor característico.",
      "É um doce com duas camadas de massa e recheio, muitas vezes de doce de leite.",
    ],
  },
  {
    answer: "Cannoli",
    tips: [
      "É uma sobremesa tradicional italiana.",
      "Originou-se na região da Sicília.",
      "Consiste em uma casca crocante e um recheio cremoso.",
      "O recheio clássico é feito de ricota adoçada.",
      "Às vezes, é adicionado chocolate ou frutas cristalizadas no recheio.",
      "A casca é frita até ficar dourada e crocante.",
      "É frequentemente polvilhado com açúcar de confeiteiro.",
      "Pode ser encontrado em padarias e confeitarias italianas.",
      "É um doce comum durante as festividades e feriados na Itália.",
      "Às vezes, a casca é mergulhada em chocolate.",
      "O recheio pode ser aromatizado com canela ou baunilha.",
      "Pode ser decorado com pistaches ou cerejas.",
      "É mencionado em várias obras de cultura pop, incluindo filmes.",
      "É um símbolo da rica tradição culinária siciliana.",
      "É uma sobremesa com uma casca frita e recheio de ricota doce.",
    ],
  },
  {
    answer: "Pastel de Nata",
    tips: [
      "É uma sobremesa tradicional portuguesa.",
      "Originou-se em um mosteiro em Lisboa.",
      "É conhecido por sua massa folhada crocante.",
      "O recheio é um creme feito com gemas de ovo, açúcar e leite.",
      "É assado até a superfície ficar levemente caramelizada.",
      "É frequentemente polvilhado com canela e açúcar em pó antes de ser servido.",
      "Tem uma textura cremosa e um sabor doce.",
      "É popular não apenas em Portugal, mas também em outros países lusófonos.",
      "Pode ser encontrado em muitas padarias e confeitarias.",
      "É tradicionalmente servido com um café expresso.",
      "Também é conhecido como 'pastel de Belém' em Lisboa.",
      "Existem receitas que datam do século XIX.",
      "É um ícone da culinária portuguesa.",
      "É apreciado por sua combinação de crocância e cremosidade.",
      "É um pequeno pastel de massa folhada com recheio de creme de ovo.",
    ],
  },
  {
    answer: "Tiramisù",
    tips: [
      "É uma sobremesa italiana clássica.",
      "Tem um nome que significa 'levanta-me' ou 'me anime'.",
      "É feito com camadas de biscoitos embebidos em café.",
      "O recheio é uma mistura de mascarpone, ovos e açúcar.",
      "Frequentemente é aromatizado com licor, como Marsala.",
      "As camadas são alternadas com uma mistura cremosa.",
      "É coberto com uma camada de cacau em pó.",
      "É uma sobremesa sem necessidade de cozimento.",
      "Deve ser refrigerado por várias horas antes de servir.",
      "O café usado é geralmente espresso forte.",
      "Pode incluir uma camada de chocolate ralado ou em pó.",
      "É uma das sobremesas mais famosas da Itália.",
      "Tem variações que incluem frutas ou outros licores.",
      "É popular em restaurantes italianos em todo o mundo.",
      "É uma sobremesa em camadas com biscoitos embebidos em café e recheio de mascarpone.",
    ],
  },
  {
    answer: "Piano",
    tips: [
      "É um instrumento.",
      "Possui teclas.",
      "Foi inventado no início do século XVIII.",
      "Pode ser acústico ou digital.",
      "É frequentemente utilizado em música clássica e jazz.",
      "Tem cordas internas que vibram quando as teclas são pressionadas.",
      "Pode ser vertical ou de cauda.",
      "Ludwig van Beethoven e Wolfgang Amadeus Mozart compuseram para ele.",
      "É conhecido pela sua ampla gama tonal e dinâmica.",
      "É um instrumento comum em concertos e apresentações.",
      "O som é produzido por martelos que batem nas cordas.",
      "Muitas casas possuem versões menores para prática doméstica.",
      "Franz Liszt e Frédéric Chopin foram famosos virtuosos deste instrumento.",
      "Pode ser usado para solos, acompanhamento ou em conjuntos.",
      "É um instrumento de teclado com cordas e martelos internos.",
    ],
  },
  {
    answer: "Caneca",
    tips: [
      "É um objeto de uso diário.",
      "Pode ser feita de cerâmica, vidro, metal ou plástico.",
      "Geralmente, tem uma alça.",
      "É usada para beber líquidos quentes ou frios.",
      "Pode ser decorada com designs, frases ou logotipos.",
      "Muitas pessoas têm uma favorita para usar em casa ou no trabalho.",
      "Pode ser encontrada em várias formas e tamanhos.",
      "É um item comum em presentes promocionais.",
      "Pode ser personalizada com fotos ou mensagens.",
      "Frequentemente, é usada para beber café ou chá.",
      "É um utensílio de cozinha essencial.",
      "Pode ser lavada à mão ou na máquina de lavar louça.",
      "Algumas têm propriedades térmicas para manter a bebida quente.",
      "Pode ser colecionada por entusiastas.",
      "É um recipiente com alça, geralmente usado para bebidas.",
    ],
  },
  {
    answer: "Bíblia",
    tips: [
      "É um texto religioso central em várias tradições.",
      "Compreende o Antigo e o Novo Testamento.",
      "É considerada a palavra de Deus por cristãos.",
      "Contém histórias, poemas, profecias e ensinamentos.",
      "Foi escrita ao longo de muitos séculos.",
      "Inclui livros como Gênesis, Salmos e Apocalipse.",
      "É a obra literária mais traduzida do mundo.",
      "Possui grande influência na cultura ocidental.",
      "Existem várias versões e traduções, como a King James e a Nova Versão Internacional.",
      "Os judeus consideram apenas o Antigo Testamento como sagrado.",
      "Os evangelhos contam a vida e os ensinamentos de Jesus.",
      "É lida e estudada em serviços religiosos e academias.",
      "Contém o Sermão da Montanha e os Dez Mandamentos.",
      "Pode ser encontrada em formato impresso e digital.",
      "É o livro sagrado do cristianismo.",
    ],
  },
  {
    answer: "Música",
    tips: [
      "É uma forma de arte e expressão.",
      "Pode ser vocal ou instrumental.",
      "Existe em todas as culturas humanas conhecidas.",
      "Pode evocar uma ampla gama de emoções.",
      "Tem elementos como melodia, harmonia e ritmo.",
      "Pode ser escrita em notação musical.",
      "É usada em cerimônias religiosas e festividades.",
      "Pode ser gravada e reproduzida em diferentes mídias.",
      "Existe em gêneros como clássica, rock, jazz e pop.",
      "Pode ser performada ao vivo em concertos e recitais.",
      "A tecnologia digital revolucionou sua produção e distribuição.",
      "Grandes compositores incluem Bach, Beethoven e Mozart.",
      "Pode ser uma carreira profissional para muitos artistas.",
      "É um meio de comunicação universal.",
      "É uma arte composta por sons organizados no tempo.",
    ],
  },
  {
    answer: "Trigonometria",
    tips: [
      "É um ramo da matemática.",
      "Estuda as relações entre os ângulos e os lados dos triângulos.",
      "É essencial para a engenharia e a física.",
      "Usa funções como seno, cosseno e tangente.",
      "Tem aplicações em navegação e astronomia.",
      "É fundamentada em conceitos geométricos.",
      "Pode ser usada para resolver problemas de triangulação.",
      "É uma parte importante do currículo escolar em matemática.",
      "A identidade fundamental é o teorema de Pitágoras.",
      "É utilizada em gráficos e ondas.",
      "O círculo unitário é uma ferramenta visual importante.",
      "Funções hiperbólicas são uma extensão do conceito.",
      "Tabelas eram usadas antes das calculadoras.",
      "É importante para o estudo de fenômenos periódicos.",
      "É a matemática dos triângulos e das funções angulares.",
    ],
  },
  {
    answer: "Fotossíntese",
    tips: [
      "É um processo realizado pelas plantas.",
      "Converte dióxido de carbono em oxigênio.",
      "Usa luz solar como fonte de energia.",
      "Produz glicose e outros carboidratos.",
      "É essencial para a vida na Terra.",
      "Ocorre nas células das folhas e caules.",
      "É uma reação química complexa.",
      "Envolve pigmentos como a clorofila.",
      "É um exemplo de produção de energia renovável.",
      "É a base da cadeia alimentar.",
      "É um dos principais processos biológicos.",
      "A equação química é 6CO2 + 6H2O → C6H12O6 + 6O2.",
      "É estudada em biologia e ecologia.",
      "É um exemplo de simbiose entre plantas e luz solar.",
      "É a conversão de luz solar em energia química pelas plantas.",
    ],
  },
  {
    answer: "Democracia",
    tips: [
      "É um sistema político.",
      "Envolve a participação dos cidadãos nas decisões do governo.",
      "Pode ser direta ou representativa.",
      "Inclui eleições livres e justas.",
      "Tem suas raízes na Grécia antiga.",
      "É baseada nos princípios da igualdade e liberdade.",
      "Inclui a separação de poderes.",
      "Protege os direitos individuais e minoritários.",
      "É um sistema de governo pluralista.",
      "É um dos pilares da sociedade moderna.",
      "Pode ser ameaçada por corrupção e autoritarismo.",
      "É um tema central na ciência política.",
      "Pode ser implementada de várias maneiras em diferentes países.",
      "É um ideal em constante evolução.",
      "É um sistema de governo onde o poder é exercido pelo povo.",
    ],
  },
  {
    answer: "Feminismo",
    tips: [
      "É um movimento social e político.",
      "Busca a igualdade de gênero.",
      "Luta contra a discriminação e o sexismo.",
      "Tem raízes históricas em várias partes do mundo.",
      "Inclui várias correntes e perspectivas.",
      "Defende os direitos das mulheres e das minorias de gênero.",
      "Promove a autonomia e a liberdade das mulheres.",
      "É um tema central nos estudos de gênero.",
      "Inclui questões como igualdade salarial e direitos reprodutivos.",
      "Pode ser criticado por sua falta de inclusão.",
      "É um movimento diverso e em constante evolução.",
      "Pode ser associado a figuras históricas como Simone de Beauvoir e Gloria Steinem.",
      "É uma luta por justiça e equidade.",
      "Pode ser praticado por pessoas de todos os gêneros.",
      "É a busca pela igualdade de direitos e oportunidades entre os gêneros.",
    ],
  },
  {
    answer: "Estratosfera",
    tips: [
      "É uma camada da atmosfera terrestre.",
      "Está situada acima da troposfera.",
      "Estende-se aproximadamente de 10 a 50 km acima da superfície da Terra.",
      "Contém a camada de ozônio.",
      "A temperatura aumenta com a altitude nesta camada.",
      "Protege a vida na Terra filtrando a radiação ultravioleta do sol.",
      "É onde aviões a jato e balões meteorológicos frequentemente voam.",
      "A ausência de turbulência é uma característica marcante.",
      "Seu nome vem do latim e significa 'camada'.",
      "Pode ser observada indiretamente através de satélites meteorológicos.",
      "Foi estudada pela primeira vez no início do século XX.",
      "Os foguetes atravessam esta camada ao entrar no espaço.",
      "Contém menos vapor de água do que a troposfera.",
      "A camada de ozônio é crucial para bloquear a radiação UVB.",
      "É a segunda camada principal da atmosfera da Terra.",
    ],
  },
  {
    answer: "Criptografia",
    tips: [
      "É uma ciência que estuda técnicas de segurança da informação.",
      "Seu objetivo principal é proteger a confidencialidade dos dados.",
      "Utiliza algoritmos para codificar e decodificar mensagens.",
      "É usada em tecnologias de comunicação modernas, como emails e transações bancárias.",
      "Existem dois tipos principais: simétrica e assimétrica.",
      "A simétrica utiliza a mesma chave para fazer e desfazer.",
      "A assimétrica utiliza um par de chaves, uma pública e uma privada.",
      "O método de substituição de César é um exemplo clássico.",
      "Foi fundamental durante a Segunda Guerra Mundial, com máquinas como a Enigma.",
      "A segurança depende da complexidade do algoritmo e do tamanho da chave.",
      "HTTPS utiliza para proteger dados na web.",
      "É crucial para garantir a integridade e autenticidade das informações.",
      "Blockchain, utilizado em criptomoedas, é baseado em seus princípios.",
      "Pode ser quebrada através de ataques, como força bruta ou criptoanálise.",
      "É a prática de proteger informações transformando-as em um formato ilegível para não autorizados.",
    ],
  },
  {
    answer: "Girassol",
    tips: [
      "É uma planta conhecida por suas grandes flores amarelas.",
      "Seu nome científico é Helianthus annuus.",
      "É nativo da América do Norte.",
      "Suas flores seguem o movimento do sol, fenômeno conhecido como heliotropismo.",
      "Pode crescer até três metros de altura.",
      "Suas sementes são uma fonte popular de óleo e alimento.",
      "Foi cultivado por povos indígenas antes da chegada dos europeus.",
      "É frequentemente cultivado por sua beleza ornamental.",
      "Suas sementes são usadas para fazer óleo de cozinha.",
      "Também é popular em produtos como manteiga de semente e granola.",
      "As flores são compostas de muitos pequenos floretes, que se desenvolvem em sementes.",
      "Simboliza lealdade e longevidade em muitas culturas.",
      "É polinizado por abelhas e outros insetos.",
      "Pode ser utilizado em rotação de culturas para melhorar a saúde do solo.",
      "É uma planta que cresce em direção ao sol e produz sementes comestíveis.",
    ],
  },
  {
    answer: "Neurônio",
    tips: [
      "É uma célula especializada do sistema nervoso.",
      "Sua função principal é transmitir informações através de impulsos elétricos.",
      "É composto por um corpo celular, dendritos e um axônio.",
      "Pode se comunicar com outras células através de sinapses.",
      "Possuem substâncias químicas liberadas nas sinapses.",
      "Existem diferentes tipos, incluindo sensoriais, motores e interneurônios.",
      "São fundamentais para todas as funções cognitivas e motoras.",
      "A mielina cobre os axônios, acelerando a transmissão dos impulsos.",
      "São incapazes de se dividir, mas podem formar novas conexões.",
      "Foram descobertos por Santiago Ramón y Cajal, que ganhou o Prêmio Nobel.",
      "Doenças como Alzheimer, afetam essas células.",
      "Podem gerar e transmitir sinais elétricos devido ao potencial de ação.",
      "Estão presentes tanto no cérebro quanto na medula espinhal.",
      "A plasticidade neural é a capacidade de formar novas conexões sinápticas.",
      "São as unidades básicas do sistema nervoso, responsáveis pela transmissão de informações.",
    ],
  },
  {
    answer: "Metamorfose",
    tips: [
      "É um processo de transformação.",
      "Ocorre em várias espécies, incluindo insetos e anfíbios.",
      "Envolve mudanças drásticas na estrutura e forma do organismo.",
      "É uma parte essencial do ciclo de vida de borboletas e sapos.",
      "O termo vem do grego e significa 'mudança de forma'.",
      "Inclui estágios como ovo, larva, pupa e adulto em insetos.",
      "Os anfíbios passam de larvas aquáticas a adultos terrestres.",
      "É controlada por hormônios específicos.",
      "As mariposas também passam por este processo.",
      "Pode ocorrer rápida ou lentamente, dependendo da espécie.",
      "O exemplo mais conhecido é o ciclo de vida da borboleta.",
      "No teatro e na literatura, pode ser usado metaforicamente.",
      "É crucial para a sobrevivência e reprodução de certas espécies.",
      "Também é observado em algumas plantas durante seu desenvolvimento.",
      "É a transformação completa que ocorre em certos organismos ao longo de seu ciclo de vida.",
    ],
  },
  {
    answer: "Simetria",
    tips: [
      "É um conceito fundamental em matemática e arte.",
      "Refere-se à correspondência equilibrada de partes opostas.",
      "Pode ser observada na natureza, como em flores e conchas.",
      "Existem diferentes tipos, incluindo bilateral e radial.",
      "Na biologia, muitas criaturas possuem este atributo.",
      "É um elemento essencial na arquitetura e design.",
      "Em matemática, é estudada através de grupos simétricos.",
      "No corpo humano, é evidente na disposição dos órgãos.",
      "Também é importante na física e na química, especialmente em cristais.",
      "Na arte, é utilizada para criar harmonia e equilíbrio visual.",
      "As asas das borboletas são um exemplo clássico.",
      "Em linguística, pode ser aplicada à estrutura de frases e palavras.",
      "Tem implicações na teoria da relatividade e mecânica quântica.",
      "Pode ser observada em padrões de comportamento e organização social.",
      "É a correspondência de partes opostas ao redor de um eixo central.",
    ],
  },
  {
    answer: "Equilíbrio",
    tips: [
      "É um estado de estabilidade.",
      "Pode ser dinâmico ou estático.",
      "É crucial para a manutenção da postura e movimento no corpo.",
      "Em física, é o estado onde as forças estão em equilíbrio.",
      "Na economia, refere-se ao ponto onde oferta e demanda se igualam.",
      "Na ecologia, é a estabilidade de um ecossistema.",
      "É uma habilidade importante para atletas e bailarinos.",
      "A orelha interna desempenha um papel vital na manutenção deste estado.",
      "Pode ser afetado por distúrbios como vertigem.",
      "Em química, ocorre quando as reações diretas e inversas se igualam.",
      "Em psicologia, pode referir-se ao emocional.",
      "No design, é a distribuição igual de elementos visuais.",
      "O conceito é aplicado em diversas áreas do conhecimento.",
      "Pode ser alcançado através de práticas como ioga e meditação.",
      "É o estado de estabilidade entre forças opostas ou influências.",
    ],
  },
  {
    answer: "Sistema Imunológico",
    tips: [
      "É uma rede complexa de células, tecidos e órgãos.",
      "Sua função principal é defender o corpo contra patógenos.",
      "Inclui células como linfócitos e fagócitos.",
      "Produz anticorpos para neutralizar invasores específicos.",
      "Pode distinguir entre células próprias e estranhas.",
      "É dividido em imunidade inata e adaptativa.",
      "O timo e a medula óssea são órgãos essenciais para sua função.",
      "As vacinas ajudam a treiná-lo para combater doenças específicas.",
      "As alergias são uma resposta exagerada deste sistema.",
      "A imunidade adaptativa é altamente específica e tem memória.",
      "As doenças autoimunes ocorrem quando ele ataca tecidos do próprio corpo.",
      "O HIV é um vírus que enfraquece este sistema.",
      "Os linfonodos são pequenos órgãos que filtram substâncias e contêm células imunológicas.",
      "Pode ser fortalecido por uma dieta equilibrada e exercícios regulares.",
      "É o sistema do corpo responsável pela defesa contra doenças e infecções.",
    ],
  },
  {
    answer: "Sensação",
    tips: [
      "É uma experiência consciente.",
      "Resulta da estimulação de órgãos sensoriais.",
      "Pode ser visual, auditiva, tátil, gustativa ou olfativa.",
      "É o primeiro passo no processo perceptual.",
      "Envolve receptores específicos para diferentes tipos de estímulos.",
      "Pode ser influenciada por fatores internos e externos.",
      "É processada inicialmente em áreas específicas do cérebro.",
      "A intensidade pode variar dependendo da força do estímulo.",
      "Pode ser agradável, desagradável ou neutra.",
      "Pode ser modulada por experiências passadas e expectativas.",
      "A percepção é a interpretação dessas experiências.",
      "Exemplos incluem ver a luz, ouvir um som ou sentir uma textura.",
      "É uma função básica necessária para a sobrevivência.",
      "Distúrbios como sinestesia afetam como ela é percebida.",
      "É a resposta inicial do corpo a estímulos externos e internos.",
    ],
  },
  {
    answer: "Movimento",
    tips: [
      "É uma característica essencial dos organismos vivos.",
      "Pode ser voluntário ou involuntário.",
      "Envolve a contração e relaxamento de músculos.",
      "É controlado pelo sistema nervoso.",
      "Pode ser suave e fluido ou rápido e abrupto.",
      "A locomoção é um tipo específico de movimento.",
      "É fundamental para a interação com o ambiente.",
      "Pode ser observado em todos os reinos biológicos.",
      "Exemplos incluem caminhar, correr e nadar.",
      "Na física, é descrito em termos de deslocamento, velocidade e aceleração.",
      "O movimento ocular é crucial para a visão.",
      "É um componente chave nas artes performáticas.",
      "A biomecânica estuda os princípios por trás dele.",
      "A prática regular de exercícios ajuda a mantê-lo eficiente.",
      "É a mudança de posição ou estado de um organismo ou objeto.",
    ],
  },
  {
    answer: "Sistema Nervoso",
    tips: [
      "É responsável pela coordenação e controle das funções do corpo.",
      "Compreende o cérebro, medula espinhal e nervos.",
      "É dividido em sistema nervoso central e periférico.",
      "Os neurônios são suas unidades básicas funcionais.",
      "Transmite sinais elétricos e químicos.",
      "Controla tanto ações voluntárias quanto involuntárias.",
      "É crucial para a percepção sensorial e resposta motora.",
      "A mielina ajuda a acelerar a transmissão de impulsos nervosos.",
      "As sinapses são os locais de comunicação entre neurônios.",
      "A neurotransmissão envolve substâncias químicas como dopamina e serotonina.",
      "Distúrbios como Parkinson e Alzheimer afetam sua função.",
      "A medula espinhal atua como uma via para sinais entre o cérebro e o corpo.",
      "É protegido por estruturas ósseas e membranas chamadas meninges.",
      "A neuroplasticidade é a capacidade de formar novas conexões sinápticas.",
      "É o sistema responsável pela comunicação e coordenação das funções corporais.",
    ],
  },
  {
    answer: "Mobília",
    tips: [
      "São objetos móveis que facilitam as atividades humanas.",
      "Incluem itens como mesas, cadeiras e camas.",
      "Podem ser feitas de madeira, metal, plástico ou outros materiais.",
      "São essenciais para a organização de espaços interiores.",
      "Desempenham tanto funções práticas quanto estéticas.",
      "Existem estilos variados, como moderno, clássico e rústico.",
      "Algumas peças são projetadas para conforto e ergonomia.",
      "Pode ser customizada para se adequar a espaços específicos.",
      "A funcionalidade é um aspecto importante em seu design.",
      "Antiguidades são valorizadas pela história e artesanato.",
      "Pode incluir itens de armazenamento como armários e estantes.",
      "É essencial em ambientes domésticos, comerciais e de trabalho.",
      "Pode ser modular para flexibilidade e adaptabilidade.",
      "O design sustentável está se tornando uma tendência crescente.",
      "São os itens que compõem e decoram os ambientes interiores.",
    ],
  },
  {
    answer: "Decoração",
    tips: [
      "Envolve a disposição e escolha de elementos estéticos em um espaço.",
      "Pode ser aplicada em ambientes internos e externos.",
      "Inclui o uso de cores, texturas e materiais.",
      "Pode refletir a personalidade e estilo dos habitantes.",
      "É usada para criar ambientes funcionais e agradáveis.",
      "Inclui móveis, acessórios e obras de arte.",
      "Estilos populares incluem moderno, rústico e minimalista.",
      "Pode ser sazonal, como decoração de Natal ou Halloween.",
      "A iluminação é um componente crucial.",
      "O feng shui é uma filosofia de decoração que busca harmonia.",
      "Pode incluir plantas e elementos naturais.",
      "A disposição de móveis pode influenciar o fluxo de energia.",
      "Pode ser DIY ou profissionalmente projetada.",
      "Tende a seguir tendências e modas.",
      "É a arte de organizar um espaço para torná-lo visualmente atraente e funcional.",
    ],
  },
  {
    answer: "Iluminação",
    tips: [
      "É essencial para a visibilidade e segurança.",
      "Pode ser natural ou artificial.",
      "A luz solar é a sua principal fonte natural.",
      "Inclui lâmpadas, luminárias e velas.",
      "Pode afetar o humor e a produtividade das pessoas.",
      "A temperatura de cor varia de quente a fria.",
      "É usada para destacar elementos de decoração.",
      "A tecnologia LED é eficiente e duradoura.",
      "Pode ser funcional, ambiental ou de destaque.",
      "O design dela é uma especialização na arquitetura.",
      "Luzes reguláveis permitem controle da intensidade.",
      "A externa é crucial para a paisagem e segurança.",
      "Pode ser usada para criar efeitos dramáticos em espetáculos.",
      "É essencial para atividades como leitura.",
      "É a aplicação de luz para melhorar a visibilidade e criar ambientes.",
    ],
  },
  {
    answer: "Estrutura",
    tips: [
      "É a base de construção de um edifício ou objeto.",
      "Pode ser de madeira, aço, concreto ou outros materiais.",
      "Suporta cargas e distribui peso.",
      "É crucial para a estabilidade e segurança de construções.",
      "Inclui fundações, paredes, colunas e vigas.",
      "Pode ser projetada para resistir a terremotos e ventos fortes.",
      "Arquitetos e engenheiros civis são os principais responsáveis pelo design.",
      "Pontes e arranha-céus dependem de estruturas robustas.",
      "A simetria e a forma influenciam sua eficiência.",
      "As que utilizam treliça são comuns em pontes e torres.",
      "A durabilidade é um fator-chave no design estrutural.",
      "Pode ser temporária ou permanente.",
      "A manutenção regular é essencial para a longevidade.",
      "O design moderno utiliza software para simulação e análise.",
      "É o esqueleto que suporta e dá forma a um edifício ou objeto.",
    ],
  },
  {
    answer: "Clima",
    tips: [
      "Refere-se às condições atmosféricas médias de uma região.",
      "É medido ao longo de longos períodos, geralmente 30 anos ou mais.",
      "Inclui fatores como temperatura, precipitação e vento.",
      "Difere-se de 'tempo'.",
      "Incluem tropical, temperada e polar.",
      "É influenciado pela latitude, altitude e proximidade de corpos d'água.",
      "Mudanças significativas podem levar a fenômenos como desertificação ou glaciação.",
      "O El Niño e La Niña são fenômenos que afetam.",
      "A mudança disso refere-se a alterações a longo prazo nas médias.",
      "Afeta a distribuição de plantas e animais.",
      "Os cientistas utilizam modelos para prever futuras mudanças.",
      "O efeito estufa é um processo natural que aquece a superfície da Terra.",
      "Ações humanas, como a queima de combustíveis fósseis, estão o alterando.",
      "A variabilidade pode resultar em eventos extremos como furacões.",
      "É o padrão de condições atmosféricas que caracteriza uma região ao longo do tempo.",
    ],
  },
  {
    answer: "Habitat",
    tips: [
      "É o ambiente natural onde vive uma espécie.",
      "Pode ser terrestre ou aquático.",
      "Fornece alimentos, água, abrigo e espaço para reprodução.",
      "Varia desde desertos áridos até florestas tropicais densas.",
      "A destruição dele é uma das principais ameaças à biodiversidade.",
      "Alguns animais são altamente especializados.",
      "Corais e recifes formam meios marinhos complexos.",
      "A conservação é crucial para a preservação de espécies.",
      "Pode ser fragmentado pela atividade humana, como construção de estradas.",
      "Os ecossistemas são compostos por múltiplos interconectados.",
      "A qualidade afeta diretamente a saúde das populações de espécies.",
      "Espécies invasoras podem degradar os nativos.",
      "Os urbanos suportam uma diversidade única de vida selvagem.",
      "Mudanças climáticas estão forçando muitas espécies a mudarem.",
      "É o lugar onde uma planta ou animal naturalmente vive e cresce.",
    ],
  },
  {
    answer: "Aracnídeo",
    tips: [
      "É uma classe de artrópodes.",
      "Inclui aranhas, escorpiões, ácaros e carrapatos.",
      "Possuem oito patas.",
      "Seus corpos são divididos em duas partes principais: cefalotórax e abdômen.",
      "Não têm antenas.",
      "Muitas espécies produzem seda.",
      "A maioria é carnívora, alimentando-se de insetos e pequenos animais.",
      "Algumas aranhas são venenosas para os humanos.",
      "Têm olhos simples em vez de compostos.",
      "Os escorpiões possuem um ferrão venenoso na cauda.",
      "Os ácaros são minúsculos e podem ser parasitas.",
      "A respiração ocorre através de pulmões foliáceos ou traqueias.",
      "São encontrados em quase todos os habitats terrestres.",
      "Têm um exoesqueleto feito de quitina.",
      "Formam um grupo de artrópodes caracterizados por oito patas e corpos segmentados.",
    ],
  },
  {
    answer: "Orangotango",
    tips: [
      "É um grande primata.",
      "Vive principalmente nas florestas tropicais de Sumatra e Bornéu.",
      "Seu nome significa 'pessoa da floresta' em malaio.",
      "Tem braços longos e pernas curtas.",
      "Passa a maior parte do tempo em árvores.",
      "É conhecido por sua inteligência e uso de ferramentas.",
      "Possui uma pelagem longa e avermelhada.",
      "Tem uma dieta principalmente frugívora.",
      "Os machos adultos desenvolvem grandes bolsas de gordura nas faces.",
      "A espécie está criticamente ameaçada devido à perda de habitat.",
      "Tem um ciclo reprodutivo lento, com um longo período de cuidado materno.",
      "Pode viver até 40 anos ou mais na natureza.",
      "É o mais solitário dos grandes primatas.",
      "Os esforços de conservação incluem a proteção de florestas e reabilitação de órfãos.",
      "É um primata arborícola de grande porte encontrado nas florestas tropicais do sudeste asiático.",
    ],
  },
  {
    answer: "Morte",
    tips: [
      "É um fenômeno universal.",
      "Marca o fim das funções biológicas de um organismo.",
      "Pode ocorrer de forma súbita ou gradual.",
      "É um dos maiores mistérios da existência humana.",
      "Pode ser causada por doenças, traumas ou envelhecimento.",
      "É um tema recorrente em filosofia e religião.",
      "Muitas culturas têm rituais específicos para lidar com ela.",
      "Seu conceito pode variar entre diferentes sociedades.",
      "Pode ser um processo natural ou induzido.",
      "Desencadeia uma série de reações químicas no corpo.",
      "Envolve a cessação das atividades cardíacas e respiratórias.",
      "A biologia moderna ainda estuda suas causas e efeitos.",
      "É o destino inevitável de todos os seres vivos.",
      "Em algumas culturas, é vista como uma transição para outra forma de existência.",
      "Pode inspirar medo, respeito ou aceitação.",
    ],
  },
  {
    answer: "DNA",
    tips: [
      "É a molécula que carrega a informação genética.",
      "Foi descoberta em meados do século XX.",
      "Tem uma estrutura de dupla hélice.",
      "Contém quatro tipos de bases nitrogenadas.",
      "É encontrado em todas as células vivas.",
      "Pode ser extraído e analisado em laboratório.",
      "Codifica as instruções para o desenvolvimento e funcionamento dos organismos.",
      "Pode sofrer mutações que afetam a saúde e aparência.",
      "É hereditário, sendo passado de pais para filhos.",
      "Suas sequências podem ser usadas para identificar indivíduos.",
      "É fundamental para a biotecnologia e a medicina moderna.",
      "Permite o estudo da evolução e da ancestralidade.",
      "Pode ser alterado através de engenharia genética.",
      "Seu estudo avançou com o Projeto Genoma Humano.",
      "É usado em testes de paternidade e em investigações criminais.",
    ],
  },
  {
    answer: "Herança",
    tips: [
      "Refere-se à transmissão de características de uma geração para outra.",
      "Pode ser genética ou cultural.",
      "Os primeiros estudos sistemáticos foram feitos por Gregor Mendel.",
      "Inclui traços físicos como cor dos olhos e altura.",
      "Também pode incluir predisposições a certas doenças.",
      "Os cromossomos desempenham um papel crucial nesse processo.",
      "Pode ser influenciada por fatores ambientais.",
      "Também se refere à transmissão de bens e propriedades.",
      "É um dos principais temas da biologia evolutiva.",
      "Pode ser estudada através de genealogia.",
      "Inclui tanto genes dominantes quanto recessivos.",
      "Permite a variação e a adaptação das espécies.",
      "Influencia comportamentos e habilidades.",
      "Pode ser rastreada por testes genéticos modernos.",
      "É fundamental para a compreensão da seleção natural.",
    ],
  },
  {
    answer: "Energia",
    tips: [
      "É essencial para a realização de trabalho.",
      "Pode existir em várias formas, como cinética e potencial.",
      "A Lei da Conservação afirma que ela não pode ser criada nem destruída.",
      "É medida em unidades como joules e calorias.",
      "Pode ser transformada de uma forma para outra.",
      "É fundamental para todos os processos biológicos.",
      "Pode ser obtida de fontes renováveis e não renováveis.",
      "A fotossíntese converte a luz solar em química.",
      "É necessária para o funcionamento de máquinas e aparelhos.",
      "O corpo humano a obtém dos alimentos.",
      "A eletricidade é uma forma amplamente utilizada.",
      "Suas fontes fósseis incluem carvão e petróleo.",
      "É um tema central nas discussões sobre sustentabilidade.",
      "O conceito de entropia está relacionado à sua dispersão.",
      "É explorada e gerida através da engenharia e da física.",
    ],
  },
  {
    answer: "Metabolismo",
    tips: [
      "É um conjunto de reações químicas que ocorrem em organismos vivos.",
      "Envolve a conversão de nutrientes em energia.",
      "Tem dois processos principais: anabolismo e catabolismo.",
      "É essencial para o crescimento e reparo celular.",
      "Pode ser influenciado por fatores genéticos e ambientais.",
      "A taxa dessas reações varia entre indivíduos.",
      "É crucial para a manutenção da homeostase.",
      "Requer a presença de enzimas específicas.",
      "Pode ser afetado por doenças como diabetes.",
      "Inclui a digestão de alimentos e a absorção de nutrientes.",
      "Desempenha um papel na regulação da temperatura corporal.",
      "Sua eficiência pode diminuir com a idade.",
      "É estudado em bioquímica e fisiologia.",
      "Alguns suplementos e dietas afirmam aumentar sua taxa.",
      "É vital para a sobrevivência de todos os organismos.",
    ],
  },
  {
    answer: "Antivírus",
    tips: [
      "É um software projetado para detectar e eliminar ameaças.",
      "Protege sistemas de arquivos contra programas maliciosos.",
      "Pode ser atualizado regularmente para combater novas ameaças.",
      "Funciona em segundo plano no seu dispositivo.",
      "Pode escanear arquivos e pastas à procura de problemas.",
      "Ajuda a proteger contra roubo de informações pessoais.",
      "É essencial para a segurança cibernética.",
      "Pode prevenir ataques de phishing e spyware.",
      "É usado tanto em computadores quanto em dispositivos móveis.",
      "Pode ter funções adicionais, como firewall e controle parental.",
      "Foi inicialmente desenvolvido para combater vírus simples.",
      "Agora combate uma ampla gama de malware.",
      "Alguns são gratuitos, outros requerem assinatura.",
      "É uma ferramenta indispensável para empresas e indivíduos.",
      "Seu desempenho pode afetar a velocidade do sistema.",
    ],
  },
  {
    answer: "Wi-Fi",
    tips: [
      "É uma tecnologia de comunicação sem fio.",
      "Permite a conexão de dispositivos à internet.",
      "Funciona através de ondas de rádio.",
      "Tem diferentes padrões, como 802.11ac e 802.11ax.",
      "É comum em residências, escritórios e espaços públicos.",
      "Requer um roteador para distribuir o sinal.",
      "Pode ser protegida por senhas e criptografia.",
      "Facilita a mobilidade e a flexibilidade de uso de dispositivos.",
      "Pode ser afetada por interferências de outros aparelhos.",
      "Permite a criação de redes locais sem a necessidade de cabos.",
      "Tem um alcance limitado, que pode ser estendido com repetidores.",
      "Sua velocidade pode variar dependendo do congestionamento.",
      "É essencial para o funcionamento de dispositivos inteligentes.",
      "A primeira versão comercial surgiu no final dos anos 90.",
      "Pode ser utilizada para transmissão de dados e multimídia.",
    ],
  },
  {
    answer: "E-mail",
    tips: [
      "É um método de comunicação digital.",
      "Permite o envio de mensagens e arquivos anexos.",
      "Utiliza protocolos como SMTP, IMAP e POP3.",
      "Pode ser acessado através de clientes de correio ou webmail.",
      "É essencial para a comunicação empresarial e pessoal.",
      "Pode incluir caixas de entrada, saída e rascunhos.",
      "Pode ser filtrado por regras e pastas específicas.",
      "É vulnerável a spam e phishing.",
      "Oferece a opção de cópia oculta (BCC) para discrição.",
      "Pode ser sincronizado em múltiplos dispositivos.",
      "Foi um dos primeiros serviços amplamente adotados na internet.",
      "Pode ser organizado por categorias ou etiquetas.",
      "Permite a assinatura digital e criptografia para segurança.",
      "Tem uma capacidade de armazenamento que pode variar.",
      "É usado diariamente por bilhões de pessoas no mundo.",
    ],
  },
  {
    answer: "Rede Social",
    tips: [
      "É uma plataforma online para interação e compartilhamento.",
      "Permite a conexão entre indivíduos e grupos.",
      "Inclui sites como Facebook, Twitter e Instagram.",
      "Pode ser usada para comunicação, entretenimento e networking.",
      "Facilita a criação e compartilhamento de conteúdo.",
      "Pode ser pública ou privada.",
      "Oferece recursos como curtidas, comentários e compartilhamentos.",
      "Pode ser usada para promover eventos e causas.",
      "Pode ser uma fonte de notícias e informações.",
      "É uma ferramenta poderosa para marketing e publicidade.",
      "Pode ser viciante e ter impactos na saúde mental.",
      "Pode ser usada para manter contato com amigos e familiares.",
      "Pode ser usada para construir comunidades e movimentos.",
      "Pode ser usada para expressar opiniões e ideias.",
      "É uma parte integrante da vida digital moderna.",
    ],
  },
  {
    answer: "Coca-Cola",
    tips: [
      "Foi inventada no século XIX.",
      "É uma das marcas mais reconhecidas no mundo.",
      "Originalmente, tinha ingredientes controversos.",
      "Sua fórmula exata é um segredo bem guardado.",
      "É conhecida por seu sabor doce e efervescente.",
      "Patrocina eventos esportivos e culturais.",
      "Tem uma cor escura característica.",
      "É frequentemente consumida gelada.",
      "Possui uma linha de produtos diet e sem açúcar.",
      "É envasada em garrafas e latas de diversos tamanhos.",
      "Seu logotipo vermelho e branco é icônico.",
      "Foi inicialmente comercializada como um tônico medicinal.",
      "Tem presença global em quase todos os países.",
      "Compete com outras grandes marcas na sua área.",
      "Utiliza campanhas publicitárias memoráveis e emocionais.",
    ],
  },
  {
    answer: "Streaming",
    tips: [
      "É uma forma de transmissão de dados em tempo real.",
      "Permite assistir a vídeos e ouvir músicas sem download completo.",
      "Requer uma conexão estável à internet.",
      "Pode ser usado em dispositivos móveis e computadores.",
      "As plataformas oferecem conteúdos sob demanda.",
      "Inclui serviços de filmes, séries, música e jogos.",
      "Pode ser gratuito com anúncios ou pago com assinatura.",
      "Facilita o acesso a conteúdos ao redor do mundo.",
      "Pode ajustar a qualidade de acordo com a velocidade da internet.",
      "Algumas plataformas produzem seus próprios conteúdos originais.",
      "Permite a transmissão ao vivo de eventos e shows.",
      "Foi popularizado na última década com o avanço da tecnologia.",
      "Oferece a possibilidade de criar listas de reprodução personalizadas.",
      "Pode ser usado para educação e treinamentos online.",
      "É uma alternativa moderna à mídia tradicional.",
    ],
  },
  {
    answer: "Café da manhã",
    tips: [
      "É a primeira refeição do dia.",
      "É consumida após um período de jejum noturno.",
      "Pode incluir alimentos doces ou salgados.",
      "É considerada importante para fornecer energia matinal.",
      "Pode variar muito entre diferentes culturas.",
      "Frequentemente inclui bebidas quentes como café ou chá.",
      "Pode ajudar na concentração e desempenho cognitivo.",
      "Alimentos comuns incluem frutas, cereais e pães.",
      "Alguns estudos associam sua importância ao metabolismo.",
      "Pode ser simples ou um banquete completo, dependendo da tradição.",
      "Muitas pessoas optam por alimentos ricos em proteínas nesta refeição.",
      "Pode incluir sucos de frutas e laticínios.",
      "É uma refeição onde suplementos e vitaminas são comumente ingeridos.",
      "Pode influenciar o humor e os níveis de energia ao longo do dia.",
      "É uma prática diária recomendada por nutricionistas.",
    ],
  },
  {
    answer: "Carboidrato",
    tips: [
      "É um macronutriente essencial para a dieta humana.",
      "Fornece a principal fonte de energia para o corpo.",
      "Pode ser encontrado em alimentos como pães, massas e arroz.",
      "Existem dois tipos principais: simples e complexos.",
      "É importante para o funcionamento do cérebro e músculos.",
      "Pode ser convertido em glicose para uso imediato.",
      "É armazenado no corpo como glicogênio.",
      "A sua ingestão deve ser balanceada para evitar problemas de saúde.",
      "Pode ser refinado ou integral, influenciando seu valor nutricional.",
      "Dietas populares frequentemente discutem sua quantidade ideal.",
      "É essencial para a recuperação pós-exercício.",
      "Influencia os níveis de açúcar no sangue.",
      "É uma parte fundamental da pirâmide alimentar.",
      "Pode ser encontrado em frutas, legumes e laticínios.",
      "Fornece fibras dietéticas quando consumido em formas não processadas.",
    ],
  },
  {
    answer: "Pimenta do reino",
    tips: [
      "É uma especiaria amplamente utilizada na culinária.",
      "Vem de uma planta que cresce em climas tropicais.",
      "Pode ser moída na hora para liberar mais sabor.",
      "Existe em variedades preta, branca e verde.",
      "Tem um sabor picante e quente.",
      "Era altamente valorizada e usada como moeda no passado.",
      "É comumente usada em pratos salgados.",
      "Pode ajudar na digestão e tem propriedades antioxidantes.",
      "É frequentemente combinada com sal em temperos.",
      "Sua planta é trepadeira e produz pequenas bagas.",
      "O grão seco é a forma mais comum encontrada nas cozinhas.",
      "Pode ser utilizada em marinadas e temperos para carnes.",
      "Tem um aroma distinto que se intensifica ao ser moída.",
      "É cultivada principalmente na Índia e no Vietnã.",
      "Pode ser encontrada em praticamente todas as cozinhas do mundo.",
    ],
  },
  {
    answer: "Fígado",
    tips: [
      "É um órgão vital no corpo humano e de outros animais.",
      "Desempenha um papel crucial na desintoxicação do organismo.",
      "Produz bile, que é importante para a digestão de gorduras.",
      "Armazena vitaminas e minerais essenciais.",
      "Participa na metabolização de carboidratos, proteínas e lipídios.",
      "Pode se regenerar após danos parciais.",
      "Filtra substâncias nocivas do sangue.",
      "Está localizado na região superior direita do abdômen.",
      "Pode ser afetado por doenças como cirrose e hepatite.",
      "É rico em nutrientes e pode ser consumido como alimento.",
      "É um dos maiores órgãos internos do corpo.",
      "Auxilia na regulação dos níveis de açúcar no sangue.",
      "Pode ser doado parcialmente para transplantes.",
      "Sua saúde é essencial para o metabolismo geral do corpo.",
      "É alvo de exames médicos para avaliar sua função e detectar doenças.",
    ],
  },
  {
    answer: "Atum",
    tips: [
      "É um peixe amplamente consumido em várias culturas.",
      "Vive em águas tropicais e temperadas.",
      "É conhecido por sua carne firme e saborosa.",
      "É uma fonte rica de proteínas e ômega-3.",
      "Pode ser consumido fresco, enlatado ou congelado.",
      "É popular em pratos como sushi e sashimi.",
      "Pode ser grelhado, assado ou servido cru.",
      "Algumas espécies podem nadar a grandes velocidades.",
      "É um dos principais peixes capturados comercialmente.",
      "Possui um corpo hidrodinâmico adaptado para nadar.",
      "Sua carne pode variar de rosa claro a vermelho profundo.",
      "Algumas variedades são consideradas delicadezas.",
      "Pode ser encontrado em saladas, sanduíches e massas.",
      "É um ingrediente comum em dietas saudáveis.",
      "Tem importância econômica para muitas nações costeiras.",
    ],
  },
  {
    answer: "Tofu",
    tips: [
      "É um alimento de origem vegetal.",
      "Feito a partir de soja.",
      "É uma fonte rica em proteínas para vegetarianos e veganos.",
      "Tem uma textura que pode variar de macia a firme.",
      "Pode ser usado em pratos doces e salgados.",
      "Absorve facilmente os sabores dos temperos e molhos.",
      "É um ingrediente comum na culinária asiática.",
      "Pode ser frito, assado, grelhado ou consumido cru.",
      "É baixo em calorias e gorduras saturadas.",
      "Contém todos os aminoácidos essenciais.",
      "Pode ser enriquecido com cálcio e ferro.",
      "Utilizado em substituição à carne em muitas receitas.",
      "Pode ser marinado para adicionar sabor.",
      "É feito através da coagulação do leite de soja.",
      "É popular em dietas saudáveis e de controle de peso.",
    ],
  },
  {
    answer: "Halloween",
    tips: [
      "É celebrado em Outubro.",
      "As pessoas se fantasiam e participam de festas temáticas.",
      "As crianças costumam ir de porta em porta pedindo doces.",
      "Tem origem em antigas tradições celtas.",
      "As abóboras esculpidas são símbolos icônicos.",
      "Casas são decoradas com temas assustadores.",
      "É comum ver filmes de terror sendo exibidos nessa época.",
      "As cores preto e laranja são associadas à festividade.",
      "O 'trick or treat' é uma atividade popular.",
      "É uma ocasião para contar histórias de fantasmas.",
      "Muitos eventos comunitários, como desfiles e feiras, acontecem.",
      "Também é conhecido por suas festas à fantasia para adultos.",
      "Os símbolos incluem bruxas, fantasmas e morcegos.",
      "Tem uma história de sincretismo entre paganismo e cristianismo.",
      "É amplamente comemorado em países de língua inglesa.",
    ],
  },
  {
    answer: "Natal",
    tips: [
      "É comemorado em Dezembro.",
      "Celebra o nascimento de uma figura central no cristianismo.",
      "As casas são decoradas com luzes e árvores.",
      "A troca de presentes é uma tradição importante.",
      "Canções festivas são cantadas e ouvidas amplamente.",
      "O Papai Noel é um personagem popular associado à data.",
      "Festas e refeições em família são comuns.",
      "Tem uma temporada de compras significativa no comércio.",
      "As cores vermelho, verde e dourado são associadas à festividade.",
      "Muitos filmes e programas de TV temáticos são exibidos.",
      "Tem raízes em tradições pagãs de inverno.",
      "É celebrado em todo o mundo, com variações regionais.",
      "As igrejas realizam missas especiais na véspera e no dia.",
      "Doces e pratos específicos são preparados nessa época.",
      "É um tempo de caridade e doação para os necessitados.",
    ],
  },
  {
    answer: "Páscoa",
    tips: [
      "É uma celebração móvel, geralmente em Abril.",
      "Comemora a ressurreição de uma figura central no cristianismo.",
      "O coelho é um símbolo popular associado à data.",
      "Os ovos decorados são um dos principais símbolos.",
      "As igrejas realizam serviços especiais durante essa época.",
      "Festas e reuniões familiares são comuns.",
      "As crianças participam de caça aos ovos.",
      "Tem raízes em tradições antigas de fertilidade.",
      "Muitas culturas têm pratos tradicionais específicos para a data.",
      "A Semana Santa precede essa celebração.",
      "Também é um feriado de primavera em muitas culturas.",
      "As cores pastéis são frequentemente usadas nas decorações.",
      "Tem um forte significado religioso para os cristãos.",
      "É um tempo de renovação e esperança.",
      "É celebrado de várias maneiras em todo o mundo.",
    ],
  },
  {
    answer: "Dia da Independência",
    tips: [
      "Celebra a libertação de um país do domínio estrangeiro.",
      "É marcado por eventos cívicos e celebrações nacionais.",
      "Fogos de artifício são uma tradição comum.",
      "Paradas e desfiles são organizados em muitas cidades.",
      "É frequentemente comemorado com discursos patrióticos.",
      "Pode incluir a exibição de bandeiras nacionais.",
      "As escolas e empresas geralmente têm o dia de folga.",
      "Muitos países têm diferentes datas para essa celebração.",
      "As famílias se reúnem para festas e piqueniques.",
      "Pode incluir cerimônias de hasteamento da bandeira.",
      "É um momento para refletir sobre a história e a identidade nacional.",
      "Concertos e apresentações musicais são comuns.",
      "Pode ter desfiles militares e exibições de força.",
      "É uma oportunidade para promover o patriotismo e a unidade.",
      "Alguns países realizam eventos esportivos especiais.",
    ],
  },
  {
    answer: "Peruca",
    tips: [
      "É usada para cobrir a cabeça.",
      "Pode ser feita de cabelo humano ou sintético.",
      "É popular em teatro e cinema para caracterização de personagens.",
      "Pode ser usada para fins médicos, como alopecia.",
      "Varia em estilos, cores e comprimentos.",
      "Era muito popular entre a nobreza europeia no passado.",
      "Pode ser usada para mudar temporariamente a aparência.",
      "É comum em competições de cosplay.",
      "Algumas são projetadas para serem indetectáveis.",
      "Pode ser usada em ocasiões festivas e temáticas.",
      "Ajuda a criar visuais dramáticos e elaborados.",
      "Existem versões específicas para diferentes épocas e culturas.",
      "Pode ser presa com grampos, fitas ou adesivos.",
      "Requer manutenção e cuidados específicos.",
      "É um acessório essencial para artistas performáticos.",
    ],
  },
  {
    answer: "Novidade",
    tips: [
      "Refere-se a algo recentemente introduzido.",
      "Pode causar interesse ou excitação nas pessoas.",
      "Frequentemente anunciada por meios de comunicação.",
      "Pode ser um produto, serviço ou informação.",
      "Tem um apelo especial devido à sua frescura.",
      "Pode rapidamente se tornar popular ou viral.",
      "Está associada à inovação e progresso.",
      "Muitas vezes, busca atrair a atenção do público.",
      "É comum em indústrias como tecnologia e moda.",
      "Pode ser temporária ou duradoura.",
      "As empresas frequentemente lançam para competir no mercado.",
      "Pode ser uma tendência que define uma era.",
      "Muitas vezes testada através de marketing experimental.",
      "Gera expectativas e curiosidade.",
      "Pode ser uma ideia ou conceito revolucionário.",
    ],
  },
  {
    answer: "Torta",
    tips: [
      "É um prato que pode ser doce ou salgado.",
      "Tem uma crosta feita de massa.",
      "Pode ser recheada com frutas, cremes ou carnes.",
      "É frequentemente servida como sobremesa.",
      "Pode ser acompanhada de sorvete ou chantilly.",
      "A crosta pode ser coberta ou aberta.",
      "É popular em muitas culturas ao redor do mundo.",
      "Pode ser assada em um forno.",
      "Alguns tipos são servidos em ocasiões especiais.",
      "Pode ser feita em diferentes formas e tamanhos.",
      "A versão doce pode incluir ingredientes como maçã ou abóbora.",
      "As versões salgadas podem incluir frango ou legumes.",
      "Tem uma longa história na culinária mundial.",
      "Pode ser comprada pronta ou feita em casa.",
      "É um item comum em padarias e confeitarias.",
    ],
  },
  {
    answer: "Canibalismo",
    tips: [
      "É um comportamento documentado em várias espécies.",
      "Envolve o consumo de indivíduos da mesma espécie.",
      "Pode ocorrer por necessidade ou ritualísticamente.",
      "Foi praticado por algumas culturas antigas.",
      "Está associado a tabus e controvérsias.",
      "Pode ser um tema em filmes de terror e literatura.",
      "Em certas situações, pode ser um ato de sobrevivência.",
      "É estudado por antropólogos e biólogos.",
      "Algumas espécies de insetos exibem esse comportamento.",
      "Pode ter implicações psicológicas e sociais profundas.",
      "Está relacionado a mitos e histórias populares.",
      "Em humanos, é amplamente condenado e ilegal.",
      "Pode ser desencadeado por fatores ambientais extremos.",
      "Algumas práticas religiosas antigas incluíam rituais desse tipo.",
      "É um comportamento extremo observado em situações desesperadoras.",
    ],
  },
  {
    answer: "Print",
    tips: [
      "Refere-se à captura de uma imagem da tela.",
      "Pode ser usada para documentar informações visuais.",
      "É frequentemente utilizada em tutoriais e guias.",
      "Pode ser feita com atalhos de teclado específicos.",
      "Pode incluir todo o monitor ou apenas uma janela selecionada.",
      "Pode ser armazenada como arquivo de imagem.",
      "É útil para relatar problemas técnicos.",
      "Pode ser editada e anotada com ferramentas gráficas.",
      "É comum em ambientes de trabalho e educação.",
      "Facilita o compartilhamento de informações visuais.",
      "Pode ser usada para evidências em conversas online.",
      "É uma funcionalidade presente em computadores e smartphones.",
      "Permite registrar layouts de sites e aplicativos.",
      "Pode capturar elementos dinâmicos como menus e diálogos.",
      "É uma prática comum entre desenvolvedores e designers.",
    ],
  },
  {
    answer: "Alergia",
    tips: [
      "É uma reação exagerada do sistema imunológico.",
      "Pode ser desencadeada por alimentos, pólen ou animais.",
      "Os sintomas podem incluir espirros, coceira e inchaço.",
      "Pode variar de leve a grave, incluindo reações anafiláticas.",
      "Anti Histamínicos são frequentemente usados para tratamento.",
      "Testes cutâneos ou sanguíneos podem identificar causas.",
      "É comum em pessoas com histórico familiar.",
      "Pode afetar a qualidade de vida e o bem-estar.",
      "Asma e eczema podem estar associados a ela.",
      "Certas estações do ano podem agravar os sintomas.",
      "Evitar os desencadeantes é a melhor prevenção.",
      "Pode surgir em qualquer idade, embora algumas sejam mais comuns na infância.",
      "Alimentos como nozes, leite e ovos são comuns causadores.",
      "Pode requerer o uso de epinefrina em emergências graves.",
      "É uma área de estudo importante na imunologia.",
    ],
  },
  {
    answer: "Capa da Invisibilidade",
    tips: [
      "É um objeto frequentemente encontrado em contos de ficção.",
      "Pode tornar o usuário indetectável a olho nu.",
      "É usada por personagens para escapar ou se esconder.",
      "Tem raízes em mitos e lendas de várias culturas.",
      "Frequentemente aparece em literatura de fantasia.",
      "É um dispositivo desejado por espiões e aventureiros.",
      "Pode ser ativada com palavras mágicas ou tecnologia avançada.",
      "Cria uma sensação de mistério e poder.",
      "É comparável a outras formas de ocultamento mágico.",
      "Inspira produtos e ideias em ciência e tecnologia.",
      "Pode ser feita de materiais aparentemente comuns.",
      "Seu uso pode levar a dilemas morais e éticos.",
      "Permite o usuário explorar lugares sem ser visto.",
      "É um símbolo de liberdade e anonimato.",
      "Tem sido um tema popular em filmes e séries de TV.",
    ],
  },
  {
    answer: "Morfina",
    tips: [
      "É um medicamento derivado da papoula.",
      "É utilizado principalmente para aliviar dor intensa.",
      "Pode ser administrada por via oral, intravenosa ou subcutânea.",
      "Tem propriedades analgésicas e sedativas.",
      "Pode causar dependência se usada por longos períodos.",
      "É classificada como um opioide.",
      "É usada em ambiente hospitalar para controle de dor pós-operatória.",
      "Pode causar efeitos colaterais como náusea e sonolência.",
      "É regulada devido ao seu potencial de abuso.",
      "Descoberta no início do século XIX.",
      "Usada no tratamento de dor crônica e aguda.",
      "Pode suprimir a respiração em doses elevadas.",
      "É um dos medicamentos mais eficazes para dor severa.",
      "Pode ser utilizada no manejo da dor de pacientes terminais.",
      "É sintetizada a partir da planta Papaver somniferum.",
    ],
  },
  {
    answer: "Lactose",
    tips: [
      "É um tipo de açúcar encontrado em produtos lácteos.",
      "É composto de glicose e galactose.",
      "Algumas pessoas têm dificuldade em digeri-la.",
      "A intolerância a ela pode causar desconforto digestivo.",
      "É comumente encontrada no leite de mamíferos.",
      "Pode ser quebrada por uma enzima específica no intestino.",
      "Substitutos sem ela são populares para intolerantes.",
      "Presente em queijos, iogurtes e sorvetes.",
      "Produtos processados frequentemente adicionam-na como ingrediente.",
      "Bebidas vegetais são alternativas para quem evita-a.",
      "Intolerância pode se desenvolver com a idade.",
      "É um importante carboidrato em dietas de bebês.",
      "Produtos fermentados têm níveis reduzidos dela.",
      "Pode ser encontrada em fórmulas infantis.",
      "Testes médicos podem diagnosticar intolerância a ela.",
    ],
  },
  {
    answer: "Salada de Frutas",
    tips: [
      "É uma mistura de diferentes tipos de frutas.",
      "Pode ser servida como sobremesa ou lanche.",
      "É frequentemente colorida e atraente visualmente.",
      "As frutas podem ser frescas, enlatadas ou congeladas.",
      "Pode ser adoçada com mel ou açúcar.",
      "Comumente inclui frutas como maçã, banana, e uva.",
      "Às vezes, é incrementada com suco de laranja ou iogurte.",
      "Pode ser servida em tigelas ou copos.",
      "É uma opção popular em eventos e festas.",
      "Pode ser refrigerada antes de servir para frescor.",
      "É uma maneira saudável de consumir vitaminas e fibras.",
      "Tem variações regionais com frutas locais.",
      "Pode incluir nozes ou folhas de hortelã para sabor extra.",
      "A preparação é rápida e fácil.",
      "É uma alternativa leve e nutritiva a sobremesas mais pesadas.",
    ],
  },
  {
    answer: "Alcateia",
    tips: [
      "É um grupo social organizado de animais.",
      "Seus membros cooperam na caça e proteção.",
      "Tem uma hierarquia com líderes dominantes.",
      "A comunicação é feita por uivos, latidos e gestos.",
      "Geralmente, são animais carnívoros.",
      "O grupo pode ocupar um grande território.",
      "O cuidado dos filhotes é uma responsabilidade coletiva.",
      "A união do grupo é essencial para a sobrevivência.",
      "Pode ser encontrada em diversas partes do mundo.",
      "A caça em grupo aumenta o sucesso predatório.",
      "Os membros mais jovens aprendem observando os mais velhos.",
      "A coesão do grupo é mantida através de rituais e interações sociais.",
      "Os membros compartilham alimento após uma caça bem-sucedida.",
      "A estrutura social é geralmente estável e disciplinada.",
      "A perda de um membro pode impactar a dinâmica do grupo.",
    ],
  },
  {
    answer: "Casaco de Pele",
    tips: [
      "É uma vestimenta feita de materiais naturais.",
      "É valorizada por seu calor e luxo.",
      "Pode ser feita de diversos tipos de animais.",
      "É frequentemente alvo de controvérsia ética.",
      "Era um símbolo de status em tempos passados.",
      "Pode ter acabamentos lisos ou texturizados.",
      "É usada principalmente em climas frios.",
      "Requer cuidados especiais para manutenção.",
      "Pode ser artificialmente recriada com materiais sintéticos.",
      "É um item de moda em desfiles de alta-costura.",
      "Sua produção pode envolver processos complexos.",
      "Algumas culturas utilizam-na em trajes tradicionais.",
      "Pode ser passada de geração em geração como herança.",
      "A legislação sobre sua produção varia entre países.",
      "Alternativas ecológicas e sustentáveis estão ganhando popularidade.",
    ],
  },
  {
    answer: "Cafeína",
    tips: [
      "É um estimulante natural encontrado em várias plantas.",
      "É consumida globalmente em bebidas populares.",
      "Pode melhorar a concentração e reduzir a fadiga.",
      "É conhecida por seu efeito energético no corpo.",
      "Presente em bebidas como café, chá e refrigerantes.",
      "Pode causar insônia se consumida em excesso.",
      "É utilizada em alguns medicamentos para dores de cabeça.",
      "Pode aumentar temporariamente a pressão arterial.",
      "Pessoas podem desenvolver tolerância a seus efeitos.",
      "Alguns atletas a usam para melhorar o desempenho.",
      "É um dos ingredientes mais estudados na nutrição.",
      "Pode causar dependência e sintomas de abstinência.",
      "Seu consumo moderado é considerado seguro para a maioria.",
      "Pode ser encontrada em forma de suplemento.",
      "É metabolizada principalmente pelo fígado.",
    ],
  },
  {
    answer: "Dipirona",
    tips: [
      "É um medicamento utilizado para aliviar a dor.",
      "Também possui propriedades antipiréticas.",
      "É conhecido por sua eficácia em casos de febre alta.",
      "Pode ser administrado por via oral, injetável ou supositório.",
      "É amplamente utilizado em países da América Latina.",
      "É prescrito para tratar dores de intensidade moderada a severa.",
      "Pode ser usado para cólicas e dores pós-operatórias.",
      "É considerado seguro quando usado conforme indicado.",
      "Tem um efeito rápido e duradouro.",
      "Pode causar efeitos colaterais como reações alérgicas.",
      "Em alguns países, seu uso é restrito ou monitorado.",
      "Não é recomendado para pessoas com certos problemas de saúde.",
      "Pode ser comprado sem prescrição médica em algumas regiões.",
      "Age bloqueando a síntese de prostaglandinas no sistema nervoso.",
      "É um dos analgésicos mais utilizados globalmente.",
    ],
  },
  {
    answer: "Resfriado",
    tips: [
      "É uma infecção viral comum do trato respiratório superior.",
      "Seus sintomas incluem coriza, tosse e dor de garganta.",
      "Geralmente não é grave, mas pode causar desconforto.",
      "É mais comum durante as estações frias.",
      "Pode ser causado por vários tipos de vírus.",
      "Não há cura, mas os sintomas podem ser tratados.",
      "A hidratação e o repouso são recomendados.",
      "Pode ser prevenido com boa higiene e lavagem das mãos.",
      "Os sintomas geralmente duram de uma semana a dez dias.",
      "É altamente contagioso e se espalha facilmente.",
      "Medicamentos como descongestionantes podem aliviar os sintomas.",
      "Suplementos de vitamina C e zinco são popularmente usados.",
      "Pode levar a complicações como infecções secundárias.",
      "Crianças e idosos são mais suscetíveis.",
      "É a causa mais comum de faltas escolares e ausências no trabalho.",
    ],
  },
  {
    answer: "Seita",
    tips: [
      "É um grupo com crenças ou práticas religiosas distintas.",
      "Muitas vezes é liderado por uma figura carismática.",
      "Pode se separar de uma religião maior ou dominante.",
      "Suas doutrinas podem ser vistas como não convencionais.",
      "Os membros frequentemente demonstram forte lealdade ao grupo.",
      "Pode operar em segredo ou de forma isolada.",
      "Pode ser alvo de controvérsias e críticas externas.",
      "Algumas têm práticas de recrutamento intensivas.",
      "Seus membros podem viver em comunidades fechadas.",
      "Pode exigir adesão a regras e estilos de vida específicos.",
      "As crenças podem abranger aspectos espirituais e proféticos.",
      "Algumas têm um impacto significativo na sociedade.",
      "Podem ser associadas a eventos históricos dramáticos.",
      "A saída do grupo pode ser difícil e traumática para os membros.",
      "As autoridades frequentemente monitoram suas atividades.",
    ],
  },
  {
    answer: "Bandeira",
    tips: [
      "É um símbolo representativo de um país ou organização.",
      "Consiste em padrões e cores específicas.",
      "É usada para mostrar identidade e solidariedade.",
      "Pode ser hasteada em mastros em locais públicos.",
      "As cores e desenhos podem ter significados simbólicos.",
      "Usada em cerimônias e eventos oficiais.",
      "Pode ser alterada ou atualizada ao longo do tempo.",
      "Muitas vezes, é um símbolo de patriotismo.",
      "É usada em manifestações esportivas e competições internacionais.",
      "O respeito por ela pode incluir rituais específicos.",
      "Pode ser usada para sinalizar intenções ou mensagens.",
      "É desenhada seguindo proporções específicas.",
      "É um elemento importante em desfiles militares.",
      "Sua criação pode ser um processo legislativo.",
      "Pode representar história, cultura e valores de uma nação.",
    ],
  },
  {
    answer: "Alzheimer",
    tips: [
      "É uma doença neurodegenerativa progressiva.",
      "Afeta principalmente a memória e outras funções cognitivas.",
      "Os sintomas iniciais incluem esquecimentos leves.",
      "Pode levar à perda de independência na vida diária.",
      "É a causa mais comum de demência em idosos.",
      "Não há cura, mas os tratamentos podem retardar os sintomas.",
      "Fatores genéticos e de estilo de vida influenciam seu desenvolvimento.",
      "Os exames de imagem cerebral ajudam no diagnóstico.",
      "Afeta a comunicação e as habilidades de linguagem.",
      "Pode causar mudanças de humor e comportamento.",
      "A idade avançada é o maior fator de risco.",
      "O apoio familiar e os cuidados especializados são essenciais.",
      "A pesquisa continua buscando melhores tratamentos e prevenção.",
      "Afeta milhões de pessoas em todo o mundo.",
      "A perda de memória recente é um sintoma típico.",
    ],
  },
  {
    answer: "Papel Higiênico",
    tips: [
      "É um produto de uso diário em banheiros.",
      "Feito de folhas finas e suaves de papel.",
      "Usado para higiene pessoal após usar o banheiro.",
      "Pode ser encontrado em rolos ou folhas individuais.",
      "É um item essencial em lares e estabelecimentos.",
      "Variável em texturas e camadas para maior conforto.",
      "Algumas versões são perfumadas ou com loção.",
      "É descartável e deve ser jogado no lixo ou vaso sanitário.",
      "Tem uma história que remonta a séculos.",
      "A produção envolve celulose e processos de fabricação específicos.",
      "Pode ser reciclável e ambientalmente amigável.",
      "É estocado em grandes quantidades durante crises.",
      "O consumo per capita varia entre países.",
      "Existem alternativas como bidês e toalhas reutilizáveis.",
      "É amplamente comercializado e sujeito a design e marketing.",
    ],
  },
  {
    answer: "Pandemia",
    tips: [
      "É uma epidemia que se espalha por vários países ou continentes.",
      "Afeta um grande número de pessoas globalmente.",
      "Pode ser causada por vírus, bactérias ou outros patógenos.",
      "Requer medidas de saúde pública para controle.",
      "A vacinação é uma ferramenta importante para prevenção.",
      "Pode ter impactos econômicos e sociais significativos.",
      "O distanciamento social e o uso de máscaras são práticas comuns.",
      "A higiene das mãos é fundamental para reduzir a transmissão.",
      "Os sistemas de saúde podem ficar sobrecarregados.",
      "Pode durar meses ou anos, dependendo do patógeno.",
      "A quarentena e o isolamento são métodos de contenção.",
      "A comunicação clara das autoridades é crucial.",
      "Pode levar ao desenvolvimento de novas vacinas e tratamentos.",
      "O rastreamento de contatos é usado para controlar a disseminação.",
      "Impacta viagens e comércio internacional.",
    ],
  },
  {
    answer: "Gripe Aviária",
    tips: [
      "É uma doença infecciosa que afeta principalmente aves.",
      "Causada por diferentes subtipos de vírus.",
      "Pode ser transmitida a humanos em casos raros.",
      "Os sintomas em aves incluem inchaço e dificuldade respiratória.",
      "Os surtos podem levar ao abate em massa de aves.",
      "Afeta a indústria avícola e a economia agrícola.",
      "Pode ser transmitida através do contato com aves infectadas.",
      "Alguns subtipos têm alta mortalidade em humanos.",
      "A vigilância e o controle em aves são essenciais para prevenção.",
      "As medidas incluem vacinação de aves e monitoramento.",
      "Pode causar sintomas semelhantes aos da gripe em humanos.",
      "Tem potencial para causar surtos e epidemias.",
      "As feiras de aves vivas são pontos críticos de transmissão.",
      "Os vírus podem sofrer mutações, aumentando a preocupação.",
      "O uso de antivirais pode ser necessário em infecções humanas.",
    ],
  },
];

export default dataThing;
